steps:
  # 1. Build Next.js production container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arween-staging:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arween-staging:$COMMIT_SHA'
      - '.'

  # 2. Push image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/arween-staging:latest'

images:
  - 'gcr.io/$PROJECT_ID/arween-staging:latest'
  - 'gcr.io/$PROJECT_ID/arween-staging:$COMMIT_SHA'

timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8'
