import {
  collection,
  doc,
  getDocs,
  getDoc,
  addDoc,
  updateDoc,
  setDoc,
  query,
  orderBy,
  serverTimestamp,
  increment,
  Timestamp,
} from "firebase/firestore";
import { db } from "@/lib/firebase";

export interface Project {
  id: string;
  title: string;
  description: string;
  status: "PLANNING" | "IN_PROGRESS" | "COMPLETED";
  overallProgress: number; // 0 - 100
  totalMeritScore: number;
  aiSummary?: string;
  keyBlockers?: string[];
  targetDate?: string;
  createdAt?: any;
  updatedAt?: any;
}

export interface DailyLog {
  id: string;
  projectId: string;
  date: string;
  title: string;
  completedTasks: string;
  blockers: string;
  progressContribution: number; // percentage increment e.g. 5, 10
  meritScore: number; // 1 - 10
  aiRationale?: string;
  createdAt?: any;
}

/**
 * Fetch all projects belonging exclusively to this user (User-isolated Firestore)
 */
export async function getUserProjects(uid: string): Promise<Project[]> {
  const projectsRef = collection(db, "users", uid, "projects");
  const q = query(projectsRef, orderBy("createdAt", "desc"));
  const snap = await getDocs(q);
  return snap.docs.map((d) => ({
    id: d.id,
    ...(d.data() as Omit<Project, "id">),
  }));
}

/**
 * Get a single project
 */
export async function getProject(uid: string, projectId: string): Promise<Project | null> {
  const ref = doc(db, "users", uid, "projects", projectId);
  const snap = await getDoc(ref);
  if (!snap.exists()) return null;
  return { id: snap.id, ...(snap.data() as Omit<Project, "id">) };
}

/**
 * Create a new project for this user
 */
export async function createProject(
  uid: string,
  data: { title: string; description: string; targetDate?: string }
): Promise<string> {
  const projectsRef = collection(db, "users", uid, "projects");
  const docRef = await addDoc(projectsRef, {
    title: data.title,
    description: data.description,
    targetDate: data.targetDate || "",
    status: "IN_PROGRESS",
    overallProgress: 0,
    totalMeritScore: 0,
    aiSummary: "โครงการเพิ่งเริ่มต้น บันทึกการทำงานประจำวันเพื่อให้ AI สรุปภาพรวมความคืบหน้า",
    keyBlockers: [],
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  return docRef.id;
}

/**
 * Fetch all daily logs for a specific project
 */
export async function getDailyLogs(uid: string, projectId: string): Promise<DailyLog[]> {
  const logsRef = collection(db, "users", uid, "projects", projectId, "daily_logs");
  const q = query(logsRef, orderBy("createdAt", "desc"));
  const snap = await getDocs(q);
  return snap.docs.map((d) => ({
    id: d.id,
    projectId,
    ...(d.data() as Omit<DailyLog, "id" | "projectId">),
  }));
}

/**
 * Add a daily log entry and directly update the project's overall progress & merit points (Rollup)
 */
export async function addDailyLog(
  uid: string,
  projectId: string,
  logData: {
    date: string;
    title: string;
    completedTasks: string;
    blockers: string;
    progressContribution: number;
    meritScore: number;
    aiRationale?: string;
  }
): Promise<string> {
  const logsRef = collection(db, "users", uid, "projects", projectId, "daily_logs");
  
  // 1. Save log document
  const logDoc = await addDoc(logsRef, {
    ...logData,
    createdAt: serverTimestamp(),
  });

  // 2. Rollup to parent Project: compute new overall progress and total score
  const projectRef = doc(db, "users", uid, "projects", projectId);
  const projSnap = await getDoc(projectRef);
  if (projSnap.exists()) {
    const currentProg = projSnap.data().overallProgress || 0;
    const newProgress = Math.min(100, Math.max(0, currentProg + logData.progressContribution));
    const newStatus = newProgress >= 100 ? "COMPLETED" : "IN_PROGRESS";

    await updateDoc(projectRef, {
      overallProgress: newProgress,
      status: newStatus,
      totalMeritScore: increment(logData.meritScore || 0),
      updatedAt: serverTimestamp(),
    });
  }

  // 3. Increment global user merit score in users/{uid}
  const userRef = doc(db, "users", uid);
  await updateDoc(userRef, {
    totalMeritScore: increment(logData.meritScore || 0),
    updatedAt: serverTimestamp(),
  }).catch(() => {});

  return logDoc.id;
}

/**
 * Update project executive summary generated by AI
 */
export async function updateProjectAIOverview(
  uid: string,
  projectId: string,
  aiSummary: string,
  keyBlockers: string[]
) {
  const projectRef = doc(db, "users", uid, "projects", projectId);
  await updateDoc(projectRef, {
    aiSummary,
    keyBlockers,
    updatedAt: serverTimestamp(),
  });
}
